-- DROP TABLE  IF EXISTS ROLE;

INSERT INTO ROLE(ID, ROLE_NAME) VALUES (1,'HR');
INSERT INTO ROLE(ID, ROLE_NAME) VALUES (2,'MANAGER');
INSERT INTO ROLE(ID, ROLE_NAME) VALUES (3,'LEADER');
INSERT INTO ROLE(ID, ROLE_NAME) VALUES (4,'MEMBER');
INSERT INTO ROLE(ID, ROLE_NAME) VALUES (5,'PUBLIC');
INSERT INTO ROLE(ID, ROLE_NAME) VALUES (6,'Test');
